# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51e19fee0addd2f17bb6efce67cbb0edbce8c75fb671403f94d50f7e00918d16bf9f625e41e7e66ab115220cc9d9db56bd8ffb728445db2301cb4f0fdacab575

test:
  secret_key_base: 265d7c5edcb3ae05b1910c2b45f0aa81ab9e788752daea25780cf7d754d3b19efd32461ebdadea5b93ece9bcbe84552922f01a354c37eed7f6e0b1ce1707879b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
